use_frameworks!

platform :ios, '8.0'

target 'KLTarBarTransition_Example' do
  pod 'KLTarBarTransition', :path => '../'

  target 'KLTarBarTransition_Tests' do
    inherit! :search_paths

    
  end
end
